### ISSUE TITLE
Some question about AU labels

### ISSUE THREAD

**Issue by juneweng** [SilverFI/ROI-Nets-pytorch#1]
It is a greate work!

I have a question, how can I get AU labels? It provided by the dataset? If I want to use AU in other FER dataset, How can I do?

Thanks for advance!

**Comment by SilverFI** [comment]
AU labels are included in dataset. There is not much difference when using other dataset. You can refer to details in paper.

**Comment by juneweng** [comment]
how can I use your code if I have no AU label just landmarks?

**Comment by SilverFI** [comment]
AU labels are necessary to run the experiment.
