### ISSUE TITLE
Some question about train the net

### ISSUE THREAD

**Issue by Vurkty** [SilverFI/ROI-Nets-pytorch#3]
Some question when I train the net on BP4D.
The test mean-F1 is around 0.61.
So, I'm thinking that is balance negative/positive samples necessary?
Or is there any tricks when I train the net?
Thank you very much!

**Comment by SilverFI** [comment]
negative:positive=2:1

**Comment by Vurkty** [comment]
Thank you!
So how can I guarantee the positive-negative ratio of all AUs at the same time?
